### PR TITLE
Integrate the backend setup into the main branch

### PR DESCRIPTION
**Pull request by AVS1508**
### Changelog:
- Set up the NestJS backend with the default Express server in `./backend/`
- Added the universal login service in `./login/`
- Added MySQL database integration in `./db/`
- Added easy-to-run scripts (DevOps) to setup all the current services (Server + DB + Login) in `./document/`
- Ongoing implementation of Docker containerization within `./document/` to make the setup process further streamlined
- Updated `README.md` for local server + DB setup documentation (in concert with GitHub Wiki page: Backend)
- Updated `.gitignore` to also ignore `.vscode/` used for individual workspace configurations

### CODE REVIEW

**Comment by AVS1508** [comment]
Additional Update: The `backend_setup` branch was created separately from the `main` branch which caused unrelated histories to conflict. A merge was processed after conflict resolution, which involved:
- Accepting both changes (current + incoming) for the `README.md`
- Accepting incoming changes for the `.gitignore` file

**Comment by suikac** [comment]
The backend branch is working on my machine.

**Comment by ChinhVu320** [comment]
What's the best way to deal with local DB credentials (in typeorm.config)? Should we include the file in .gitignore, since everyone's is different?

**Comment by AVS1508** [comment]
@ChinhVu320 You could store the credentials in a `.env` file as environment variables and then use `dotenv` NPM package to access those environment variables in any file in or nested under the root folder.

**Comment by AVS1508** [comment]
@suikac Sounds good! The `backend_setup` branch was essentially created without setting the base as `main` branch, which yielded the error of unrelated histories. My 2 commits fixed that issue by merging unrelated histories using `--allow-unrelated-histories` flag followed by resolving the conflicts. This essentially merged the base of main into the backend_setup branch and now it is `n` commits ahead of the main branch without having any divergent commits.

**Comment by suikac** [comment]
@AVS1508 Sounds gret, I haven't notice that. Thank you for pointing out.

**Review by suikac — APPROVED** [review]
Backend working on my machine

**Review by mcappucci1 — APPROVED** [review]

**Review by rdp2001 — APPROVED** [review]

**Review by ChinhVu320 — APPROVED** [review]
All good!!!!

**Pull request merged**
